DROP TABLE IF EXISTS pupils;
DROP TABLE IF EXISTS exams;
DROP TABLE IF EXISTS olymp_result;
DROP TABLE IF EXISTS olympiads;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS faculty;
DROP TABLE IF EXISTS subjects;
